/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Auto-generated by vite-plugin-env
interface ImportMetaEnv {
  /**
   * - `default`  bar
   * - `dev`  bar
   * - `prod`  bar
   */
  readonly VITE_FOO: string
  /**
   * - `default`  6666
   * - `dev`  6666
   * - `prod`  '6666'
   */
  readonly VITE_NUM: number | string
  /**
   * - `default` basic
   * - `dev` basic
   * - `prod` basic
   */
  readonly VITE_BASIC: string
  /**
   * ```text
   * previous line intentionally left blank
   * ```
   * - `default` after_line
   * - `dev` after_line
   * - `prod` after_line
   */
  readonly VITE_AFTER_LINE: string
  /**
   * - `default` 
   * - `dev` 
   * - `prod` 
   */
  readonly VITE_EMPTY: string
  /**
   * - `default` 
   * - `dev` 
   * - `prod` 
   */
  readonly VITE_EMPTY_SINGLE_QUOTES: string
  /**
   * - `default` 
   * - `dev` 
   * - `prod` 
   */
  readonly VITE_EMPTY_DOUBLE_QUOTES: string
  /**
   * - `default` 
   * - `dev` 
   * - `prod` 
   */
  readonly VITE_EMPTY_BACKTICKS: string
  /**
   * - `default` single_quotes
   * - `dev` single_quotes
   * - `prod` single_quotes
   */
  readonly VITE_SINGLE_QUOTES: string
  /**
   * - `default`     single quotes    
   * - `dev`     single quotes    
   * - `prod`     single quotes    
   */
  readonly VITE_SINGLE_QUOTES_SPACED: string
  /**
   * - `default` double_quotes
   * - `dev` double_quotes
   * - `prod` double_quotes
   */
  readonly VITE_DOUBLE_QUOTES: string
  /**
   * - `default`     double quotes    
   * - `dev`     double quotes    
   * - `prod`     double quotes    
   */
  readonly VITE_DOUBLE_QUOTES_SPACED: string
  /**
   * - `default` double "quotes" work inside single quotes
   * - `dev` double "quotes" work inside single quotes
   * - `prod` double "quotes" work inside single quotes
   */
  readonly VITE_DOUBLE_QUOTES_INSIDE_SINGLE: string
  /**
   * - `default` { port: $MONGOLAB_PORT}
   * - `dev` { port: $MONGOLAB_PORT}
   * - `prod` { port: $MONGOLAB_PORT}
   */
  readonly VITE_DOUBLE_QUOTES_WITH_NO_SPACE_BRACKET: string
  /**
   * - `default` single 'quotes' work inside double quotes
   * - `dev` single 'quotes' work inside double quotes
   * - `prod` single 'quotes' work inside double quotes
   */
  readonly VITE_SINGLE_QUOTES_INSIDE_DOUBLE: string
  /**
   * - `default` `backticks` work inside single quotes
   * - `dev` `backticks` work inside single quotes
   * - `prod` `backticks` work inside single quotes
   */
  readonly VITE_BACKTICKS_INSIDE_SINGLE: string
  /**
   * - `default` `backticks` work inside double quotes
   * - `dev` `backticks` work inside double quotes
   * - `prod` `backticks` work inside double quotes
   */
  readonly VITE_BACKTICKS_INSIDE_DOUBLE: string
  /**
   * - `default` backticks
   * - `dev` backticks
   * - `prod` backticks
   */
  readonly VITE_BACKTICKS: string
  /**
   * - `default`     backticks    
   * - `dev`     backticks    
   * - `prod`     backticks    
   */
  readonly VITE_BACKTICKS_SPACED: string
  /**
   * - `default` double "quotes" work inside backticks
   * - `dev` double "quotes" work inside backticks
   * - `prod` double "quotes" work inside backticks
   */
  readonly VITE_DOUBLE_QUOTES_INSIDE_BACKTICKS: string
  /**
   * - `default` single 'quotes' work inside backticks
   * - `dev` single 'quotes' work inside backticks
   * - `prod` single 'quotes' work inside backticks
   */
  readonly VITE_SINGLE_QUOTES_INSIDE_BACKTICKS: string
  /**
   * - `default` double "quotes" and single 'quotes' work inside backticks
   * - `dev` double "quotes" and single 'quotes' work inside backticks
   * - `prod` double "quotes" and single 'quotes' work inside backticks
   */
  readonly VITE_DOUBLE_AND_SINGLE_QUOTES_INSIDE_BACKTICKS: string
  /**
   * - `default` expand\nnew\nlines
   * - `dev` expand\nnew\nlines
   * - `prod` expand\nnew\nlines
   */
  readonly VITE_EXPAND_NEWLINES: string
  /**
   * - `default` dontexpand\nnewlines
   * - `dev` dontexpand\nnewlines
   * - `prod` dontexpand\nnewlines
   */
  readonly VITE_DONT_EXPAND_UNQUOTED: string
  /**
   * - `default` dontexpand\nnewlines
   * - `dev` dontexpand\nnewlines
   * - `prod` dontexpand\nnewlines
   */
  readonly VITE_DONT_EXPAND_SQUOTED: string
  /**
   * ```text
   * COMMENTS2=work
   * COMMENTS3=work
   * COMMENTS4=work
   * COMMENTS5=work
   * work #very #well
   * ```
   * - `default` inline comments 
   * - `dev` inline comments 
   * - `prod` inline comments 
   */
  readonly VITE_INLINE_COMMENTS: string
  /**
   * ```text
   * work
   * ```
   * - `default` inline comments outside of #singlequotes
   * - `dev` inline comments outside of #singlequotes
   * - `prod` inline comments outside of #singlequotes
   */
  readonly VITE_INLINE_COMMENTS_SINGLE_QUOTES: string
  /**
   * ```text
   * work
   * ```
   * - `default` inline comments outside of #doublequotes
   * - `dev` inline comments outside of #doublequotes
   * - `prod` inline comments outside of #doublequotes
   */
  readonly VITE_INLINE_COMMENTS_DOUBLE_QUOTES: string
  /**
   * ```text
   * work
   * ```
   * - `default` inline comments outside of #backticks
   * - `dev` inline comments outside of #backticks
   * - `prod` inline comments outside of #backticks
   */
  readonly VITE_INLINE_COMMENTS_BACKTICKS: string
  /**
   * ```text
   * number sign. no space required.
   * ```
   * - `default` inline comments start with a
   * - `dev` inline comments start with a
   * - `prod` inline comments start with a
   */
  readonly VITE_INLINE_COMMENTS_SPACE: string
  /**
   * - `default` equals==
   * - `dev` equals==
   * - `prod` equals==
   */
  readonly VITE_EQUAL_SIGNS: string
  /**
   * - `default` {"foo": "bar"}
   * - `dev` {"foo": "bar"}
   * - `prod` {"foo": "bar"}
   */
  readonly VITE_RETAIN_INNER_QUOTES: string
  /**
   * - `default` {"foo": "bar"}
   * - `dev` {"foo": "bar"}
   * - `prod` {"foo": "bar"}
   */
  readonly VITE_RETAIN_INNER_QUOTES_AS_STRING: string
  /**
   * - `default` {"foo": "bar's"}
   * - `dev` {"foo": "bar's"}
   * - `prod` {"foo": "bar's"}
   */
  readonly VITE_RETAIN_INNER_QUOTES_AS_BACKTICKS: string
  /**
   * - `default`     some spaced out string
   * - `dev`     some spaced out string
   * - `prod`     some spaced out string
   */
  readonly VITE_TRIM_SPACE_FROM_UNQUOTED: string
  /**
   * - `default` therealnerdybeast@example.tld
   * - `dev` therealnerdybeast@example.tld
   * - `prod` therealnerdybeast@example.tld
   */
  readonly VITE_USERNAME: string
  /**
   * - `default`  parsed
   * - `dev`  parsed
   * - `prod`  parsed
   */
  readonly VITE_SPACED_KEY: string
  /**
   * - `default` skip_local
   * - `dev` skip_local
   * - `prod` skip_local
   */
  readonly VITE_SKIP_LOCAL: string
  /**
   * ```text
   * #666*​/
   * ```
   * - `dev` only_dev 
   */
  readonly VITE_ONLY_DEV?: string
  /**
   * - `prod` only_prod
   */
  readonly VITE_ONLY_PROD?: string
}